---
image: docker.io/nerzhul/archlinux:2016.10.01
services:
  - elasticsearch:2.4.2

before_script:
  - pacman --noconfirm -Sy openssl hiredis cppunit postgresql libmicrohttpd libmariadbclient lua
# These are already included in image
# - pacman --noconfirm -S libxml2 jsoncpp curl

stages:
  - build
  - unittests

build:gcc6:
  stage: build
  environment: staging
  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
      - build/
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DENABLE_UNITTESTS=1 ..
    - make -j4

build:clang:
  stage: build
  environment: staging
  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
      - build/
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DENABLE_UNITTESTS=1 ..
    - make -j4

.unittests_template: &unittests_definition
  stage: unittests
  environment: staging
  script:
    - cd build
    - ./src/unittests/winterwind_unittests $GITLAB_API_KEY elasticsearch

unittests:gcc6:
  <<: *unittests_definition
  dependencies:
    - build:gcc6

unittests:clang:
  <<: *unittests_definition
  dependencies:
    - build:clang
