---
image: docker.io/nerzhul/archlinux:cpp-latest

variables:
  POSTGRES_DB: unittests_db
  POSTGRES_USER: unittests
  POSTGRES_PASSWORD: "un1Ttests"
  ES_HOST: elasticsearch
  MYSQL_DATABASE: unittests_db
  MYSQL_USER: unittests
  MYSQL_PASSWORD: "un1Ttests"
  MYSQL_ROOT_PASSWORD: "useless"

before_script:
  - pacman --noconfirm -Sy openssl hiredis cppunit postgresql libmicrohttpd libmariadbclient lua websocketpp asio valgrind curl openssl-1.0 libircclient log4cplus jsoncpp curl libxml2

stages:
  - cppcheck
  - build
  - documentation
  - test
  - deploy

cppcheck:
  stage: cppcheck
  environment: staging
  before_script:
    - pacman --noconfirm -Sy cppcheck openssl-1.0
  script:
    - mkdir -p cppcheck_tests
    - cd cppcheck_tests
    - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
    - cppcheck --enable=warning,performance --project=compile_commands.json

build:gcc:
  stage: build
  environment: staging
  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
      - build/
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DENABLE_UNITTESTS=1 ..
    - make -j4

build:clang:
  stage: build
  environment: staging
  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
      - build/
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DENABLE_UNITTESTS=1 ..
    - make -j4

.tests_template: &tests_definition
  stage: test
  environment: staging
  services:
    - elasticsearch:5.4
    - postgres:latest
    - mysql:latest
  dependencies:
    - build:clang
  script:
    - cd build
    - ./src/unittests/winterwind_unittests

unittests:gcc:
  <<: *tests_definition
  dependencies:
    - build:gcc

unittests:clang:
  <<: *tests_definition

unittests:elasticsearch2:
  <<: *tests_definition
  services:
    - elasticsearch:2
    - postgres:latest
    - mysql:latest

unittests:valgrind:
  <<: *tests_definition
  script:
    - cd build
    - valgrind --leak-check=full --undef-value-errors=no --error-exitcode=9 ./src/unittests/winterwind_unittests

unittests:callgrind:
  <<: *tests_definition
  script:
    - cd build
    - valgrind --tool=callgrind ./src/unittests/winterwind_unittests
  artifacts:
    when: on_success
    expire_in: 3 day
    paths:
      - build/callgrind.out.*

codecov:gcov:
  <<: *tests_definition
  dependencies:
    - build:gcc
  script:
    - curl -O https://ftp.unix-experience.fr/lcov-1.13-2-any.pkg.tar.xz
    - pacman --noconfirm -U lcov-1.13-2-any.pkg.tar.xz
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=Debug -DENABLE_COVERAGE=1
    - make winterwind_coverage
  artifacts:
    when: on_success
    expire_in: 1 year
    paths:
      - build/winterwind_coverage

doxygen:documentation:
  stage: documentation
  environment: production
  only:
    - master
  artifacts:
      when: on_success
      expire_in: 1 year
      paths:
        - build/doc/html
  dependencies:
    - build:gcc
    - build:clang
  before_script:
    - pacman --noconfirm -Sy archlinux-keyring
    - pacman --noconfirm -Sy doxygen cmake jsoncpp libxml2
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DENABLE_UNITTESTS=1 ..
    - make doc

pages:
  stage: deploy
  only:
    - master
  dependencies:
    - doxygen:documentation
    - codecov:gcov
  script:
    - mkdir -p public/ public/coverage/
    - cp -R build/doc/html/* public/
    - cp -R build/winterwind_coverage/* public/coverage/
  artifacts:
    when: on_success
    expire_in: 1 year
    paths:
      - public
