---
image: docker.io/nerzhul/archlinux:2016.10.01
services:
  - elasticsearch:2.4.2

before_script:
  - pacman --noconfirm -Sy openssl hiredis cppunit postgresql libmicrohttpd
# These are already included in image
# - pacman --noconfirm -S libxml2 jsoncpp curl

gcc5:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DENABLE_UNITTESTS=1 ..
    - make -j4
    - ./src/unittests/winterwind_unittests $GITLAB_API_KEY

clang:
  stage: build
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DENABLE_UNITTESTS=1 ..
    - make -j4
    - ./src/unittests/winterwind_unittests $GITLAB_API_KEY
