---
image: docker.io/nerzhul/archlinux:2016.10.01
services:
  - elasticsearch:5.2
  - postgres:latest

variables:
  POSTGRES_DB: unittests_db
  POSTGRES_USER: unittests
  POSTGRES_PASSWORD: "un1Ttests"

before_script:
  - pacman --noconfirm -Sy archlinux-keyring
  - pacman --noconfirm -Sy openssl hiredis cppunit postgresql libmicrohttpd libmariadbclient lua cppcheck websocketpp asio valgrind
# These are already included in image
# - pacman --noconfirm -S libxml2 jsoncpp curl

stages:
  - cppcheck
  - build
  - unittests

cppcheck:
  stage: cppcheck
  environment: staging
  script:
    - mkdir -p cppcheck_tests
    - cd cppcheck_tests
    - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
    - cppcheck --enable=warning,performance --project=compile_commands.json

build:gcc6:
  stage: build
  environment: staging
  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
      - build/
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DENABLE_UNITTESTS=1 ..
    - make -j4

build:clang:
  stage: build
  environment: staging
  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
      - build/
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DENABLE_UNITTESTS=1 ..
    - make -j4

.unittests_template: &unittests_definition
  stage: unittests
  environment: staging
  script:
    - cd build
    - ./src/unittests/winterwind_unittests $GITLAB_API_KEY $TWITTER_CONSUMER_KEY $TWITTER_CONSUMER_SECRET $TWITTER_ACCESS_TOKEN $TWITTER_ACCESS_TOKEN_SECRET elasticsearch

unittests:gcc6:
  <<: *unittests_definition
  dependencies:
    - build:gcc6

unittests:clang:
  <<: *unittests_definition
  dependencies:
    - build:clang

unittests:valgrind:
  <<: *unittests_definition
  dependencies:
    - build:clang
  script:
      - cd build
      - valgrind --undef-value-errors=no ./src/unittests/winterwind_unittests $GITLAB_API_KEY $TWITTER_CONSUMER_KEY $TWITTER_CONSUMER_SECRET $TWITTER_ACCESS_TOKEN $TWITTER_ACCESS_TOKEN_SECRET elasticsearch
