---
image: docker.io/nerzhul/archlinux:2016.10.01

variables:
  POSTGRES_DB: unittests_db
  POSTGRES_USER: unittests
  POSTGRES_PASSWORD: "un1Ttests"
  ES_HOST: elasticsearch

before_script:
  - pacman --noconfirm -Sy archlinux-keyring
  - pacman --noconfirm -Sy openssl hiredis cppunit postgresql libmicrohttpd libmariadbclient lua websocketpp asio valgrind curl openssl-1.0
# These are already included in image
# - pacman --noconfirm -S libxml2 jsoncpp curl

stages:
  - cppcheck
  - build
  - documentation
  - unittests
  - deploy

cppcheck:
  stage: cppcheck
  environment: staging
  before_script:
    - pacman --noconfirm -Sy archlinux-keyring
    - pacman --noconfirm -Sy cppcheck openssl-1.0 openssl
  script:
    - mkdir -p cppcheck_tests
    - cd cppcheck_tests
    - cmake -DCMAKE_EXPORT_COMPILE_COMMANDS=ON ..
    - cppcheck --enable=warning,performance --project=compile_commands.json

build:gcc6:
  stage: build
  environment: staging
  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
      - build/
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DENABLE_UNITTESTS=1 ..
    - make -j4

build:clang:
  stage: build
  environment: staging
  artifacts:
    when: on_success
    expire_in: 1 day
    paths:
      - build/
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DENABLE_UNITTESTS=1 ..
    - make -j4

.unittests_template: &unittests_definition
  stage: unittests
  environment: staging
  services:
    - elasticsearch:5.2
    - postgres:latest
  dependencies:
    - build:clang
  script:
    - cd build
    - ./src/unittests/winterwind_unittests

unittests:gcc6:
  <<: *unittests_definition
  dependencies:
    - build:gcc6

unittests:clang:
  <<: *unittests_definition

unittests:elasticsearch2:
  <<: *unittests_definition
  services:
    - elasticsearch:2
    - postgres:latest

unittests:valgrind:
  <<: *unittests_definition
  script:
    - cd build
    - valgrind --leak-check=full --undef-value-errors=no --error-exitcode=9 ./src/unittests/winterwind_unittests

unittests:callgrind:
  <<: *unittests_definition
  script:
    - cd build
    - valgrind --tool=callgrind ./src/unittests/winterwind_unittests
  artifacts:
    when: on_success
    expire_in: 3 day
    paths:
      - build/callgrind.out.*

doxygen:documentation:
  stage: documentation
  environment: production
  only:
    - master
  artifacts:
      when: on_success
      expire_in: 1 year
      paths:
        - build/doc/html
  dependencies:
    - build:gcc6
    - build:clang
  before_script:
    - pacman --noconfirm -Sy archlinux-keyring
    - pacman --noconfirm -Sy doxygen cmake jsoncpp libxml2
  script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DENABLE_UNITTESTS=1 ..
    - make doc

pages:
  stage: deploy
  only:
    - master
  dependencies:
    - doxygen:documentation
  script:
    - mkdir public/
    - cp -R build/doc/html/* public/
  artifacts:
    when: on_success
    expire_in: 1 year
    paths:
      - public
